rb=boxplot(Time.s.~Treat,data=karol_sib,outline=F,ylim=c(0,35),names=c("CONT","SHAM","SHAM SIB","SIB 0.1","SIB 0.5","SIB 1.5","SIB 5.0","AMI 10","INDO 10"),ylab="Reaction Time (s)")
xi=seq(rb$n)
points(mn.t,pch=18)
points(3,30,pch=8)
points(5.9,30,pch=8)
points(6,30,pch=8)
points(6.1,30,pch=8)
points(6.9,30,pch=8)
points(7,30,pch=8)
points(7.1,30,pch=8)
points(8.95,30,pch=8)
points(9.05,30,pch=8)
points(mn.t-sd.t,pch=18)
points(mn.t+sd.t,pch=18)
dev.copy(postscript,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_sib.ps')
dev.off()
dev.copy(jpeg,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_sib.jpg',width=900)
dev.off()
dev.copy(tiff,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_sib.tif', width=900)
dev.off()
par(cex=1.1)
rb.1=boxplot(Time.s.~Treat,data=karol_sib1,outline=F,ylim=c(0,35),names=c("CONT","SHAM","SHAM SIB","SIB 1.5","AMI 10","INDO 10"),ylab="Reaction Time (s)")
xi.1=seq(rb.1$n)
points(mn.t.1,pch=18)
points(2,30,pch=8)
points(3,30,pch=8)
points(5,30,pch=8)
points(3.95,30,pch=8)
points(4.05,30,pch=8)
points(5.95,30,pch=8)
points(7.05,30,pch=8)
points(6.95,30,pch=8)
points(6.05,30,pch=8)
points(mn.t.1-sd.t.1,pch=18)
points(mn.t.1+sd.t.1,pch=18)
dev.copy(postscript,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_sib1.ps')
dev.off()
dev.copy(jpeg,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_sib1.jpg',width=600)
dev.off()
dev.copy(tiff,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_sib1.tif', width=600)
dev.off()
rb.2=boxplot(Time.s.~Treat,data=karol_sib2,outline=F,ylim=c(0,35),names=c("CONT","SIB 0.1","SIB 0.5","SIB 1.5","SIB 5.0"),ylab="Reaction Time (s)")
xi.2=seq(rb.2$n)
points(mn.t.2,pch=18)
points(3.9,30,pch=8)
points(4,30,pch=8)
points(4.1,30,pch=8)
points(4.9,30,pch=8)
points(5,30,pch=8)
points(5.1,30,pch=8)
points(mn.t.2-sd.t.2,pch=18)
points(mn.t.2+sd.t.2,pch=18)
dev.copy(postscript,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_sib2.ps')
dev.off()
dev.copy(jpeg,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_sib2.jpg',width=600)
dev.off()
dev.copy(tiff,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_sib2.tif', width=600)
dev.off()
rb.b=barplot(mn.t,lwd=2,col=NA,ylim=c(0,24),names.arg=c("CONT","SHAM","SHAM SIB","SIB 0.1","SIB 0.5","SIB 1.5","SIB 5.0","AMI 10","INDO 10"),ylab="Reaction Time (s)")
arrows(rb.b,mn.t,rb.b,mn.t+sd.t,code=2,angle=90,lty=1,lwd=1,length=0.1)
points(3.1,17,pch=8)
points(6.6,20,pch=8)
points(6.7,20,pch=8)
points(6.8,20,pch=8)
points(7.8,23,pch=8)
points(7.9,23,pch=8)
points(8,23,pch=8)
points(10.25,20,pch=8)
points(10.35,20,pch=8)
dev.copy(postscript,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_sib_bar.ps')
dev.off()
dev.copy(jpeg,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_sib_bar.jpg',width=900)
dev.off()
dev.copy(tiff,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_sib_bar.tif', width=900)
dev.off()
rb.b.1=barplot(mn.t.1,lwd=2,col=NA,ylim=c(0,20),names.arg=c("CONT","SHAM","SHAM SIB","SIB 1.5","AMI 10","INDO 10"),ylab="Reaction Time (s)")
arrows(rb.b.1,mn.t.1,rb.b.1,mn.t.1+sd.t.1,code=2,angle=90,lty=1,lwd=1,length=0.1)
points(3.1,16,pch=8)
points(4.18,19.6,pch=8)
points(4.3,19.6,pch=8)
points(4.42,19.6,pch=8)
points(5.5,16.5,pch=8)
points(6.63,19.5,pch=8)
points(6.77,19.5,pch=8)
points(1.9,14,pch=8)
dev.copy(postscript,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_sib_bar1.ps')
dev.off()
dev.copy(jpeg,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_sib_bar1.jpg',width=600)
dev.off()
dev.copy(tiff,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_sib_bar1.tif', width=600)
dev.off()
rb.b.2=barplot(mn.t.2,lwd=2,col=NA,ylim=c(0,24),names.arg=c("CONT","SIB 0.1","SIB 0.5","SIB 1.5","SIB 5.0"),ylab="Reaction Time (s)")
arrows(rb.b.2,mn.t.2,rb.b.2,mn.t.2+sd.t.2,code=2,angle=90,lty=1,lwd=1,length=0.1)
points(5.38,23.5,pch=8)
points(5.5,23.5,pch=8)
points(5.62,23.5,pch=8)
points(4.18,20,pch=8)
points(4.3,20,pch=8)
points(4.42,20,pch=8)
dev.copy(postscript,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_sib_bar2.ps')
dev.off()
dev.copy(jpeg,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_sib_bar2.jpg',width=600)
dev.off()
dev.copy(tiff,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_sib_bar2.tif', width=600)
dev.off()
par(fig=c(0,1,.15,1))
rb.io=boxplot(Time.s.~Treat,data=karol_io,outline=F,ylim=c(0,25),names=c("CONT","SIB 1.5","SHAM SIB","CONT","SIB 1.5","SHAM SIB"),ylab="Reaction Time (s)")
xi.io=seq(rb.io$n)
points(mn.t.io,pch=18)
points(1.95,20,pch=8)
points(2.05,20,pch=8)
points(2.9,20,pch=8)
points(3,20,pch=8)
points(3.1,20,pch=8)
points(4.95,20,pch=8)
points(5.05,20,pch=8)
points(6,20,pch=8)
points(mn.t.io-sd.t.io,pch=18)
points(mn.t.io+sd.t.io,pch=18)
par(fig=c(0,1,0,1),new=TRUE)
plot(x=c(5.1,10),y=c(0.25,0.25),pch=NA,xlab=NA,ylab=NA,axes=F,type="l",xlim=c(0,10),ylim=c(0,5))
par(cex=0.9)
legend(x=5.5,y=0.2,"Iohimbine 2.0mg/kg",bty="n")
dev.copy(postscript,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_io.ps')
dev.off()
dev.copy(jpeg,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_io.jpg', width=600 )
dev.off()
dev.copy(tiff,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_io.tif', width=600)
dev.off()
par(fig=c(0,1,.15,1))
par(cex=1.1)
rb.b.io=barplot(mn.t.io,lwd=2,col=NA,ylim=c(0,20),names.arg=c("CONT","SIB 1.5","SHAM SIB","CONT","SIB 1.5","SHAM SIB"),ylab="Reaction Time (s)")
arrows(rb.b.io,mn.t.io,rb.b.io,mn.t.io+sd.t.io,code=2,angle=90,lty=1,lwd=1,length=0.1)
points(1.83,14,pch=8)
points(1.97,14,pch=8)
points(3,16,pch=8)
points(3.1,16,pch=8)
points(3.22,16,pch=8)
points(5.43,14,pch=8)
points(5.57,14,pch=8)
points(6.7,16,pch=8)
par(fig=c(0,1,0,1),new=TRUE)
plot(x=c(5.1,10),y=c(0.25,0.25),pch=NA,xlab=NA,ylab=NA,axes=F,type="l",xlim=c(0,10),ylim=c(0,5))
par(cex=1.2)
legend(x=5.5,y=0.22,"Iohimbine 2.0mg/kg",bty="n",cex=0.9)
dev.copy(postscript,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_io_bar.ps',height=8.5,width=8.5,paper="letter",horiz=F)
dev.off()
dev.copy(jpeg,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_io_bar.jpg',width=600)
dev.off()
dev.copy(tiff,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_io_bar.tif', width=600)
dev.off()
par(fig=c(0,1,.15,1))
par(cex=1.1)
rb.res=boxplot(Time.s.~Treat,data=karol_res,outline=F,ylim=c(0,35),names=c("CONT","SIB 1.5","SHAM","CONT","SIB 1.5","SHAM"),boxwex=0.6,ylab="Reaction Time (s)")
xi.res=seq(rb.res$n)
points(mn.t.res,pch=18)
points(1.95,33,pch=8)
points(2.05,33,pch=8)
points(4.95,33,pch=8)
points(5.05,33,pch=8)
points(mn.t.res-sd.t.res,pch=18)
points(mn.t.res+sd.t.res,pch=18)
par(fig=c(0,1,0,1),new=TRUE)
plot(x=c(5.0,9.9),y=c(0.25,0.25),pch=NA,xlab=NA,ylab=NA,axes=F,type="l",xlim=c(0,10),ylim=c(0,5))
par(cex=.9)
legend(x=5.6,y=0.3,"Reserpine 5.0mg/kg",bty="n")
dev.copy(postscript,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_res.ps')
dev.off()
dev.copy(jpeg,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_res.jpg' )
dev.off()
dev.copy(tiff,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_res.tif')
dev.off()
par(fig=c(0,1,.15,1))
par(cex=1.1)
rb.b.res=barplot(mn.t.res,lwd=2,col=NA,ylim=c(0,26),xlim=c(0,4.8),width=0.6,space=0.3,names.arg=c("CONT","SIB 1.5","SHAM","CONT","SIB 1.5","SHAM"),ylab="Reaction Time (s)")
arrows(rb.b.res,mn.t.res,rb.b.res,mn.t.res+sd.t.res,code=2,angle=90,lty=1,lwd=1,length=0.1)
points(1.16,20,pch=8)
points(1.28,20,pch=8)
points(1.4,20,pch=8)
points(3.48,25,pch=8)
points(3.60,25,pch=8)
points(3.72,25,pch=8)
par(fig=c(0,1,0,1),new=TRUE)
plot(x=c(5.2,9.9),y=c(0.22,0.22),pch=NA,xlab=NA,ylab=NA,axes=F,type="l",xlim=c(0,10),ylim=c(0,5))
par(cex=0.9)
legend(x=5.7,y=0.2,"Reserpine 5.0mg/kg",bty="n")
dev.copy(postscript,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_res_bar.ps',height=8.5,width=8.5,paper="letter",horiz=F)
dev.off()
dev.copy(jpeg,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_res_bar.jpg' )
dev.off()
dev.copy(tiff,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_res_bar.tif')
dev.off()
par(fig=c(0,1,.15,1))
par(cex=1.1)
rb.res.ami=boxplot(Time.s.~Treat,data=karol_res_ami,outline=F,ylim=c(0,20),names=c("CONT","AMI 10","SHAM","CONT","AMI 10","SHAM"),boxwex=0.6,ylab="Reaction Time (s)")
xi.res.ami=seq(rb.res.ami$n)
points(mn.t.res.ami,pch=18)
points(1.95,20,pch=8)
points(2.05,20,pch=8)
points(mn.t.res.ami-sd.t.res.ami,pch=18)
points(mn.t.res.ami+sd.t.res.ami,pch=18)
par(fig=c(0,1,0,1),new=TRUE)
plot(x=c(5.0,9.9),y=c(0.25,0.25),pch=NA,xlab=NA,ylab=NA,axes=F,type="l",xlim=c(0,10),ylim=c(0,5))
par(cex=.9)
legend(x=5.6,y=0.3,"Reserpine 5.0mg/kg",bty="n")
dev.copy(postscript,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_res.ami.ps')
dev.off()
dev.copy(jpeg,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_res.ami.jpg' )
dev.off()
dev.copy(tiff,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_res.ami.tif')
dev.off()
par(fig=c(0,1,.15,1))
par(cex=1.1)
rb.b.res.ami=barplot(mn.t.res.ami,lwd=2,col=NA,ylim=c(0,18),xlim=c(0,4.8),width=0.6,space=0.3,names.arg=c("CONT","AMI 10","SHAM","CONT","AMI 10","SHAM"),ylab="Reaction Time (s)")
arrows(rb.b.res.ami,mn.t.res.ami,rb.b.res.ami,mn.t.res.ami+sd.t.res.ami,code=2,angle=90,lty=1,lwd=1,length=0.1)
points(1.14,17,pch=8)
points(1.26,17,pch=8)
points(1.38,17,pch=8)
points(1.92,12.5,pch=8)
points(2.04,12.5,pch=8)
points(2.16,12.5,pch=8)
points(3.59,11.5,pch=167)
par(fig=c(0,1,0,1),new=TRUE)
plot(x=c(5.2,9.9),y=c(0.22,0.22),pch=NA,xlab=NA,ylab=NA,axes=F,type="l",xlim=c(0,10),ylim=c(0,5))
par(cex=0.9)
legend(x=5.7,y=0.25,"Reserpine 5.0mg/kg",bty="n")
dev.copy(postscript,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_res.ami_bar.ps',height=8.5,width=8.5,paper="letter",horiz=F)
dev.off()
dev.copy(jpeg,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_res.ami_bar.jpg' )
dev.off()
dev.copy(tiff,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_res.ami_bar.tif')
dev.off()
par(fig=c(0,1,.15,1))
par(cex=1.1)
rb.res.vpa=boxplot(Time.s.~Treat,data=karol_res_vpa,outline=F,ylim=c(0,20),names=c("CONT","VPA 50","SHAM","CONT","VPA 50","SHAM"),boxwex=0.6,ylab="Reaction Time (s)")
xi.res.vpa=seq(rb.res.vpa$n)
points(mn.t.res.vpa,pch=18)
points(1.95,20,pch=8)
points(2.05,20,pch=8)
points(mn.t.res.vpa-sd.t.res.vpa,pch=18)
points(mn.t.res.vpa+sd.t.res.vpa,pch=18)
par(fig=c(0,1,0,1),new=TRUE)
plot(x=c(5.0,9.9),y=c(0.25,0.25),pch=NA,xlab=NA,ylab=NA,axes=F,type="l",xlim=c(0,10),ylim=c(0,5))
par(cex=.9)
legend(x=5.6,y=0.3,"Reserpine 5.0mg/kg",bty="n")
dev.copy(postscript,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_res.vpa.ps')
dev.off()
dev.copy(jpeg,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_res.vpa.jpg' )
dev.off()
dev.copy(tiff,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_res.vpa.tif')
dev.off()
par(fig=c(0,1,.15,1))
par(cex=1.1)
rb.b.res.vpa=barplot(mn.t.res.vpa,lwd=2,col=NA,ylim=c(0,22),xlim=c(0,4.8),width=0.6,space=0.3,names.arg=c("CONT","VPA 50","SHAM","CONT","VPA 50","SHAM"),ylab="Reaction Time (s)")
arrows(rb.b.res.vpa,mn.t.res.vpa,rb.b.res.vpa,mn.t.res.vpa+sd.t.res.vpa,code=2,angle=90,lty=1,lwd=1,length=0.1)
points(1.14,21,pch=8)
points(1.26,21,pch=8)
points(1.38,21,pch=8)
points(2.05,13.5,pch=8)
points(3.49,19.5,pch=8)
points(3.61,19.5,pch=8)
points(3.73,19.5,pch=8)
par(fig=c(0,1,0,1),new=TRUE)
plot(x=c(5.2,9.9),y=c(0.22,0.22),pch=NA,xlab=NA,ylab=NA,axes=F,type="l",xlim=c(0,10),ylim=c(0,5))
par(cex=1)
legend(x=5.3,y=0.25,"Reserpine 5.0mg/kg",bty="n")
dev.copy(postscript,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_res.vpa_bar.ps',height=8.5,width=8.5,paper="letter",horiz=F)
dev.off()
dev.copy(jpeg,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_res.vpa_bar.jpg' )
dev.off()
dev.copy(tiff,'E:/HDE/Helder1/Trabalhos/Production/Pain/graphs/karol_res.vpa_bar.tif')
dev.off()
